- name: AWX Test and Live Server Deployment
  hosts: localhost
  collections:
    - kubernetes.core
  gather_facts: no
  vars:
    websites:
      - name: awxtest
        host: awxtest.yekcan.com
        content: "Test surum burada."
      - name: awxlive
        host: awxlive.yekcan.com
        content: "Live surum burada."
  tasks:
    - name: Her site için Nginx Deployment Oluştur
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            namespace: default
            name: "{{ item.name }}-web-server"
            labels:
              app: "{{ item.name }}-web"
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: "{{ item.name }}-web"
            template:
              metadata:
                labels:
                  app: "{{ item.name }}-web"
              spec:
                containers:
                  - name: nginx
                    image: nginx:latest
                    ports:
                      - containerPort: 80
                    volumeMounts:
                      - name: web-content
                        mountPath: /usr/share/nginx/html
                volumes:
                  - name: web-content
                    configMap:
                      name: "{{ item.name }}-web-content"
      loop: "{{ websites }}"

    - name: Her site için sayfa içeriği oluştur
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: "{{ item.name }}-web-content"
            namespace: default
          data:
            index.html: |
              <!DOCTYPE html>
              <html>
              <head>
              <title>{{ item.name | capitalize }} Web Server</title>
              </head>
              <body>
              <h1>{{ item.name | capitalize }} Web Server</h1>
              <p>{{ item.content }}</p>
              </body>
              </html>
      loop: "{{ websites }}"

    - name: Her site için servis oluşturma
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: "{{ item.name }}-web-service"
            namespace: default
          spec:
            type: ClusterIP
            selector:
              app: "{{ item.name }}-web"
            ports:
              - port: 80
                targetPort: 80
      loop: "{{ websites }}"

    - name: Her site için Ingress Yapılandırıldı
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: networking.k8s.io/v1
          kind: Ingress
          metadata:
            name: "{{ item.name }}-web-ingress"
            namespace: default
            annotations:
              kubernetes.io/ingress.class: "nginx"
          spec:
            rules:
            - host: "{{ item.host }}"
              http:
                paths:
                  - path: /
                    pathType: Prefix
                    backend:
                      service:
                        name: "{{ item.name }}-web-service"
                        port:
                          number: 80
      loop: "{{ websites }}"
