---
- hosts: localhost
  gather_facts: no
  collections:
    - kubernetes.core
  tasks:
    - name: Kubernetes koleksiyonunun yüklü olduğunu kontrol et
      assert:
        that:
          - "kubernetes.core" in ansible_collections
        msg: "Kubernetes koleksiyonu yüklü değil. 'ansible-galaxy collection install kubernetes.core' komutunu kullanarak yükleyin."

    - name: Pod oluştur
      kubernetes.core.k8s:
        state: present
        definition: |
          apiVersion: v1
          kind: Pod
          metadata:
            name: "k8stest-v1"
            namespace: default
            labels:
              app: galaxy
          spec:
            containers:
              - name: k8stest
                image: busybox
