---
- name: NFS Hostuna Nginx Kur ve HTML Sayfası Oluştur
  hosts: nfs
  become: yes
  vars:
    html_content: "<h1>Merhaba Dünya!</h1><p>Bu sayfa {{ ansible_hostname }} üzerinde çalışıyor.</p>"
  tasks:
    - name: Nginx'i Yükle
      apt:
        name: nginx
        state: latest
      when: ansible_os_family == "Debian"

    - name: HTML Dosyasını Oluştur
      copy:
        content: "{{ html_content }}"
        dest: /var/www/html/index.html

    - name: Nginx Servisini Yeniden Başlat
      service:
        name: nginx
        state: restarted
