---
- name: Windows'a txt dosyası oluşturup içine değişkenleri yaz
  hosts: windows
  vars:
    txt_dosya_yolu: C:\\Users\\Administrator\\Desktop\\deneme.txt
    username: "KullaniciAdiOrnegi"
    password: "SifreOrnegi"
  tasks:
    - name: deneme.txt dosyasına değişken değerleri yaz
      win_shell: |
        $dosyaYolu = "{{ txt_dosya_yolu }}"
        $icerik = "deger1: {{ username }}`r`ndeger2: {{ password }}"
        $icerik | Out-File -FilePath $dosyaYolu -Encoding UTF8 -Append
