---
- name: Windows Txt
  hosts: 192.168.2.135
  gather_facts: false
  vars:
    txt_dosya_yolu: C:\\Users\\Administrator\\Desktop\\deneme2.txt
    deger1: '{{ PASSWORD }}'
    deger2: '{{ USERNAME }}'
    deger3: '{{ CLIENTID }}'
    deger4: '{{ SISTEM }}'
  tasks:
    - name: deneme.txt dosyasına değişken değerleri yaz
      win_shell: |
        $dosyaYolu = "{{ txt_dosya_yolu }}"
        $icerik = "Şifre: {{ deger1 }}`r`ndeger2: {{ deger2 }}`r`ndeger3: {{ deger3 }}`r`ndeger4: {{ deger4 }}"
        $icerik | Out-File -FilePath $dosyaYolu -Encoding UTF8 -Append
